version: "3"
services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    command: [ "postgres", "-p", "5432" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: parser_wiki
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"


volumes:
  postgres_data:
