"""add unique constraint title+cuisine

Revision ID: 85c833f120b9
Revises: b923ceb6b949
Create Date: 2025-08-31 18:17:45.829722

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '85c833f120b9'
down_revision: Union[str, None] = 'b923ceb6b949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recipes_search_vector', table_name='recipes', postgresql_using='gin')
    op.create_unique_constraint('uq_recipe_title_cuisine', 'recipes', ['title', 'cuisine'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_recipe_title_cuisine', 'recipes', type_='unique')
    op.create_index('idx_recipes_search_vector', 'recipes', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
